learnrxjs.io is also an amazing resource for learning RxJS in preparation for RxJS Live! On Air.

Ben Lesh



RxJS Core Team Technical Lead

Former Angular Team at Google, Previously at Netflix
Gen Ashley



Founder, TECH(K)NOW
Ambassador, Google Women Techmakers
Zack DeRose



Senior Engineer
Narwhal Technologies
Younes Jaaidi



Google Developer Expert for Angular & Web Technologies
Estefania Garcia Gallardo



Full Stack Software Developer & Author, Npkill Project
Carlos Caballero



Associate Professor, Open University Catalonia, holds a Masters in Software Engineering in AI & Phd in Computer Science
Jan-Niklas Wortmann



RxJS Core Team Member
Deborah Kurata



Google Developer Expert
Software Developer, Consultant, Pluralsight Author
Matthew Podwysocki 



Software Engineer, Microsoft
Open Sourcerer
Lamis Chebbi



Google Developer Expert (GDE) for Angular
Senior software Engineer, Vermeg
Tane Piper



Open Source Developer
Josep Sobrepere



Front End Architect
Adaptive Financial Consulting